before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: YcHvvKpM+/r72LKjkidLhJ9jOY9+cdSDKufYEo8RiVbQZDAqZnPnulRHC+yEl4GXHRCyRsSvacRA6zX61GzZS6/fkCGxvrJVXg+Rv/6F6kjBSYSTpQe5XzXDO3rXYlvuniue2AVyroE5upmd6/t/detQ+w6aZ1ITuY1ltGIVXDFXsCBws9qS5W0Iux5AHMBNWlG819WhXEHE4R0pfCN0MtkSeb37uY3+W5LFFbnoF+mv6+hFc77qlYWmZAPcbU0BtUWJjUR1as4n6YOshUOKmwJ2YrpHMpvVhDROPUBBZhpTbr818Ly8RdrlriAqi6AP1PvVmPZfhoeoA0ftylUDoeHtfmiMJrkfXgYTqlatELoWAk54F/DV9eWNuoi7JnFHv2wViCZrYglnHaQMSTUb5s48Vh0q+RpZWhDzBA8KU+vld7LMJ5RZPxp1tv3vIQTl48d8vomdaf++5rrxy1gQld4Ib5T/COmJZllZnwpNurpFl7AMvoA8bccb/ZeMFP13ms+mp7GLoLOHr/X+CgWR2laFaBG3QHnfdMhh3CuGuP2AWqHvB4lVlc/TwBX8RfVEint3k/+YoeHC3I0qyacv46LYoaWai3sSKZu5BnOaWDIG+yUsT4zcsi0qvXmU8pvjZEAZmnLu88JPkOTX/jeTKsbIIDj2YMAIjHupuJjGQcE= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
